lenguage: node_js

cache:
  directories: 
    - node_modules
    - ~/.npm

node_js:
  - '15'

git: 
  depth: 3

branches:
  only: 
  - CI

script:
  - npm run test

notifications:
  slack:
    secure: "CX1xe+9PCdOn8/d8aBGglKwt2D9lP2GFrniRMMjz+T8Yb51QK/ya8sHayjNoTIXpkD9traGnlqLO2pek4qLdmm3AZsBiFYuDgAGM7GyZrchZXRzCYunYH4Slew7YmFvp4/ChIZmLjEOyqq4/gwP+64YSAXV6lBWd3+Ub1Yveb/VfOSInmJ1iEJ87zOPBMG3GxvQWz753rcMT/qkrDdFYzfziud9XOi7cDUyQbO7qVaLPYr+/MSaSXa1kQCWquC4HCACsfDn1f71Z/lsOZ+77rQIcERuI5o9sUBhKKnTWGEM51+YgfYQJUs2pVz1fRmksHrRLqW3Wd+vdK6Hn3EzzA2knHo+Qhqz0fX1AfaXeLjFzAk4Nlmh2WZQwAgORNBjXa8ZqwEcGZ/BiomdxNNpziJN4Mz23qjKlE9hSDcuUVEU0eyklLBnvy/4OR2OCFGbG8U1SUthXbhJGPIWge8jvRGh54D9EQz5Z43NEkrTpbSOuSi1XXAPtU+jBZuMRaTED4XCBynYMCykZsLw9UOewC2lI/2GxHRTGNogfH8wBWmEwoQdynAfeXCTYURTyPXx7UApw8hDej/WChRNH8mFDkOA8SwmMvCTX6BfelFcvFTK8ofUJqSYBmbbIM3NZ36whUNw5XMI6Sz5ACCxvzaCXQ7qs/o/AuXZC8IZ1/MIYzKM="

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key:
    secure: "H1ymKQ8LI+gChA9uUKfvgeSBoQfnR7VoHv1QpFsczPoJenR7Id7uYYCITXF1KdmGIu9R6WHPCUy88f2IOYly5OatXJcSIeHEj762r5G0+DR9BA3ycm8xY3qCOmty0irEuZLaLyjDfiliR+H198IbFe98K39xtf/HEH0KoguG3eHmH3J9WqjfT8PyIPQGpn9Y2nLzjQqUh5m2eSQwhCNEqd6MTMep3I25/q4toYdX2oPjsvARBfGNhiJcNc0PNCgt2zN7tBVfJj/3FNF32pGsppMcYCHG6dRc31JRDu5pwWLvu1e/aGUc2IhK3AkYO8MappV3jy98hyDFfZG5cs0NGwKst0tKw+M0x2G420vqaNbnU0zsW00jXaKdbDQZs65EBziZWtC/TJRUoySBO+AHE8gCOhNEjhVE4Wkf5TXZwVvghBMB1/skXG7N9C2Gbd+Yc28Ymx5AKEzMErIs1GZur8/25Bxk7na4pMpt9oDk4SvARNNsAEBc34C0OKnarSmLYcl6hFYB35B/79Ox+Xr+7DXzt8YIfdCLHh9UMZU+iBjMKCI+xHcJQn+qsQ2cqCSkEoELJHcvXLONcmtcbbCUcGiwdDfshZE4KP6f1QmQtljQGyiMNXltFQsoadv68Xko9btGusDFfxAy0jF+LFCGNaRoTZJFeEchTcIudjBvJxE="
  app: ingenieriadesofware
  on: 
    repo: William10101995/ministeriodesarrolloproductivo
    branch: CI
